language: node_js
node_js:
  - 5.9.0
before_script:
  - npm install

branches:
  except:
    - gh-pages

addons:
  code_climate:
    repo_token: f32a3edd8d14eab7fe1b5606ae76f34b0ae400fcf4fc1e9d4fd9a8ef4fe17c34
